# docker-compose.yml
version: '3.1'

services:

  catalog-cli:
    build: ./catalog-cli
    environment:
      MICRO_REGISTRY: "mdns"

  catalog-service:
    build: ./catalog-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
